# Generated by Django 3.2.3 on 2021-06-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General Physician', 'General Physician'), ('InfectiousDisease Physician', 'InfectiousDisease Physician'), ('Anesthesiologists', 'Anesthesiologists'), ('Pulmonologist', 'Pulmonologist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Allergists', 'Allergists'), ('Dermatologists', 'Dermatologists'), ('Ayurveda', 'Ayurveda'), ('Homoeopath', 'Homoeopath'), ('Dentist', 'Dentist')], default='General Physician', max_length=50)),
                ('about', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.ManyToManyField(to='home.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('appointment_date', models.DateField(auto_now=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Waiting')], null=True)),
                ('symptoms', models.ManyToManyField(blank=True, null=True, to='home.Symptom')),
            ],
        ),
    ]
