# Generated by Django 3.1.1 on 2021-06-27 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('General Physician', 'General Physician'), ('InfectiousDisease Physician', 'InfectiousDisease Physician'), ('Anesthesiologists', 'Anesthesiologists'), ('Pulmonologist', 'Pulmonologist'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Allergists', 'Allergists'), ('Dermatologists', 'Dermatologists'), ('Ayurveda', 'Ayurveda'), ('Homoeopath', 'Homoeopath'), ('Dentist', 'Dentist')], default='General Physician', max_length=50)),
                ('about', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symptoms', models.ManyToManyField(to='home.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('appointment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Confirmed'), (0, 'Waiting'), (-1, 'Cancelled')], default=0, null=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('doctor_id', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.ManyToManyField(to='home.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bookappointment')),
            ],
        ),
    ]
