# Generated by Django 3.1.1 on 2021-06-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_departments_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='fees_submitted',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
