# Generated by Django 3.2.3 on 2021-06-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210611_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='patient',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
