# Generated by Django 3.1.1 on 2021-06-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookappointment_fees_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='fees_submitted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
