# Generated by Django 3.2.3 on 2021-06-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210611_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
