# Generated by Django 3.1.1 on 2021-06-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210628_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
