# Generated by Django 3.2.3 on 2021-06-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_bookappointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='date',
        ),
        migrations.CreateModel(
            name='AppointmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bookappointment')),
            ],
        ),
    ]
