# Generated by Django 3.1.1 on 2021-06-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210628_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
