# Generated by Django 3.1.1 on 2021-06-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210628_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='symptoms',
        ),
        migrations.DeleteModel(
            name='AppointmentRecord',
        ),
        migrations.DeleteModel(
            name='BookAppointment',
        ),
    ]
