# Generated by Django 3.2.3 on 2021-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210611_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
