# Generated by Django 3.1.1 on 2021-06-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210630_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
