# Generated by Django 3.1.1 on 2021-07-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='symptoms',
            field=models.ManyToManyField(to='home.Symptom'),
        ),
    ]
