# Generated by Django 3.2.3 on 2021-06-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210611_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
