# Generated by Django 3.2.3 on 2021-06-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_bookappointment_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Confirmedd'), (2, 'Cancelled'), (3, 'Waiting')], null=True),
        ),
    ]
