# Generated by Django 3.2.3 on 2021-06-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_bookappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Confirmedd'), (2, 'Waiting'), (0, 'Cancelled')], null=True),
        ),
    ]
