# Generated by Django 3.2.3 on 2021-06-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_bookappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Confirmed'), (0, 'Waiting'), (-1, 'Cancelled')], default=0, null=True),
        ),
    ]
