# Generated by Django 3.2.3 on 2021-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Hospital'), (4, 'Admin')], default=1, null=True),
        ),
    ]
