# Generated by Django 3.2.3 on 2021-06-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='gender',
        ),
    ]
