# Generated by Django 3.2.3 on 2021-06-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_hospital_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='no_of_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
