# Generated by Django 3.1.1 on 2021-06-27 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Admin')], default=2, null=True)),
                ('clinic', models.CharField(blank=True, max_length=100, null=True)),
                ('open_time', models.TimeField(blank=True, default='09:00', help_text='09:00', null=True)),
                ('close_time', models.TimeField(blank=True, default='15:00', help_text='09:00', null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('fees', models.IntegerField(blank=True, default=100, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, default='07/16/1997', null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('cnt', models.IntegerField(default=0)),
                ('degree', models.ManyToManyField(to='doctor.Degree')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
