# Generated by Django 3.2.3 on 2021-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='fees',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
