# Generated by Django 3.1.1 on 2021-07-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='close_time',
            field=models.TimeField(blank=True, default='15:00', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='open_time',
            field=models.TimeField(blank=True, default='09:00', null=True),
        ),
    ]
