# Generated by Django 3.2.3 on 2021-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210611_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic_close_time',
            field=models.TimeField(blank=True, help_text='09:00', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_open_time',
            field=models.TimeField(blank=True, help_text='09:00', null=True),
        ),
    ]
