# Generated by Django 3.1.1 on 2021-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='patient_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
