# Generated by Django 3.1.1 on 2021-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_bookappointment_patient_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='doctor_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
