# Generated by Django 3.2.3 on 2021-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctor_clinic_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic_close_time',
            field=models.TimeField(blank=True, default='15:00', help_text='09:00', null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, default='07/16/1997', null=True),
        ),
    ]
