# Generated by Django 3.2.3 on 2021-06-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_close_time',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='clinic_open_time',
            new_name='open_time',
        ),
    ]
