# Generated by Django 3.1.1 on 2021-07-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_bookappointment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
